name: Daily News Scraper

on:
  schedule:
    # Run daily at 6:00 AM UTC (adjust timezone as needed)
    # To change schedule: edit this cron expression
    # Format: 'minute hour day month weekday'
    # Examples:
    #   '0 8 * * *'     = 8:00 AM UTC daily
    #   '0 12 * * *'    = 12:00 PM UTC daily
    #   '0 6 * * 1-5'   = 6:00 AM UTC weekdays only
    #   '0 6,18 * * *'  = 6:00 AM and 6:00 PM UTC daily
    - cron: '30 16 * * *'  # TEMPORARY: Test run at 16:30 UTC today
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json
        
    - name: Run news scraper
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python ground_news_scraper.py
        
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scraper-logs
        path: |
          *.log
          ground_news_results_*.csv
          explainer_script_*.txt
        retention-days: 30
